blog/urls.py
from . import views, views_posts, views_questions
from django.urls import path
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [

		# Feeds
    path("feed/rss", LatestPostsFeed(), name='post_feed'),
		
		# index
		path('', views.index, name="index" ),
		path('categories', views.categories, name="categories"),
		path('about', views.about, name='about'),
		path('filter', views.filter, name="filter"),
		path('search', views.search, name="search"),
		path('subscribe', views.subscribe, name="subscribe"),
		path('subscribed/<int:pk>/', views.subscribed, name="subscribed"),
		path('unsubscribe/<int:pk>/', views.unsubscribe, name="unsubscribe"),
		path('unsubscribed/<int:pk>/', views.unsubscribed, name="unsubscribed"),
		path('resubscribe/<int:pk>/', views.resubscribe, name="resubscribe"),
		
		path('admin/images/', views.images, name="images"),
		path('admin/images/group/<int:pk>/', views.images_group, name="images_group"),
		path('admin/images/<int:image_id>/', views.image_detail, name="image_detail"),

		# posts
		path("posts", views_posts.index, name="posts_index"),
		path('posts/<slug:slug>/', views_posts.detail, name='posts_detail'),
		path('posts/last/<int:days>/', views_posts.last_posts, name='posts_last'),
		path('posts/categories/<int:pk>/', views_posts.category_detail, name='posts_category'),

		# questions
		path("questions", views_questions.index, name="questions_index"),
		path("questions/ask", views_questions.ask, name='questions_ask'),
		path('questions/<int:pk>/', views_questions.detail, name='questions_detail'),
		path('questions/last/<int:days>/', views_questions.last_questions, name='questions_last'),
		path('questions/categories/<int:pk>/', views_questions.category_detail, name='questions_category'),

		path('logout', views.logout, name="logout")
]

healthtorch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_summernote.fields import SummernoteTextField

class Category(models.Model):
	"""
	The Categories of the posts under which they are made
	"""
	name = models.CharField(max_length=30)

	def __str__(self):
			return self.name

class ImageGroup(models.Model):
	"""
	Stores the image groups forexample:
		1. Users
		2. Posts
		3. Questions etc
	"""
	name = models.CharField(max_length=50)
	description = models.TextField(blank=True)

	def __str__(self):
		return self.name

class Image(models.Model):
	""" 
	Stores all the images of the System
	"""
	title = models.CharField(max_length=50)
	data = models.TextField(blank=True)
	group = models.ForeignKey(
		ImageGroup, on_delete=models.SET_NULL, null=True, blank=True,
		related_name="images")
	description = models.TextField(blank=True)
	
	def __str__(self):
		return self.title

class Profile(models.Model):
	"""
	Stores extra information about the user
	"""
	user = models.OneToOneField(
		User, on_delete=models.CASCADE)
	title = models.CharField(max_length=30, blank=True)
	phone = models.CharField(max_length=15, blank=True)
	facebook = models.CharField(verbose_name='Facebook Username',
		max_length=20, blank=True)
	bio = models.TextField(blank=True)
	address = models.CharField(max_length=100, blank=True)
	qualification = models.CharField(max_length=100, blank=True)
	profession = models.CharField(max_length=100, blank=True)
	employment = models.CharField(max_length=100, blank=True)
	position = models.CharField(max_length=100, blank=True)
	experience = models.PositiveIntegerField(default=0)
	image = models.ForeignKey(
		Image, on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		return self.title +' ' + self.user.first_name + ' ' + self.user.last_name 
	
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

class Subscriber(models.Model):
	"""
	Store all the Users Who Subscribe for timely updates
	"""
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(max_length=100)
	subscribed = models.BooleanField(default=True)

	def __str__(self):
		return self.email
	
	def name(self):
		return self.first_name + ' ' + self.last_name

class About(models.Model):
	site_title = models.CharField(max_length=200)
	info = models.TextField()
	last_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "About Us"

class Partner(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=100)
	phone = models.CharField(max_length=30)
	website = models.CharField(max_length=100)
	address = models.CharField(max_length=400)
	image = models.ForeignKey(
		Image, related_name="partners", on_delete=models.SET_NULL, 
		null=True, blank=True)
	description = SummernoteTextField()
	active = models.BooleanField(default=True)
	created_on = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		ordering = ['-created_on']

	def __str__(self):
		return self.name

blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from .models_posts import PostComment
from .models_questions import Question, QuestionComment

class PostCommentForm(forms.ModelForm):
	class Meta:
		model = PostComment
		fields = ('name', 'email', 'body')

		widgets = {
			'body': SummernoteWidget()
		}

class QuestionCommentForm(forms.ModelForm):
	class Meta:
		model = QuestionComment
		fields = ('name', 'email', 'body')

		widgets = {
			'body': SummernoteWidget()
		}

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ('name', 'email', 'category', 'content')

		widgets = {
			'content': SummernoteWidget()
		}

blog/views.py
import base64
import datetime
from django.views import generic
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import (Paginator, PageNotAnInteger, EmptyPage)
from django.contrib.auth.models import Group, User

from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.utils import timezone
from django.contrib.postgres.search import SearchQuery, SearchVector

from .models import Image, ImageGroup, Category, Subscriber, About, Partner
from .models_posts import Post
from .models_questions import Question


def set_context(request, context, search=True):
	context['c_user'] = request.user
	context['search'] = search
	context['categories'] = Category.objects.all()
	context['partners'] = Partner.objects.filter(active=True)
	
def about(request):
	author_group = Group.objects.filter(name="Authors")[0]
	authors = User.objects.filter(groups=author_group.id)
	about = About.objects.all()
	
	if about:
		about = about[0]

	context = {
			'authors': authors,
			'about': about,
			'atabout': True,
			"title": "About Us"
		}
	set_context(request, context, False)

	return render(	
		request,
		"blog/about.html",
		context
	)

def convert_image(file):
	blob = file.read()
	b64 = base64.b64encode(blob)
	img_str = b64.decode('UTF-8')
	return img_str	

def index(request):
	"""
	returns the: 
	1. recent three posts
	2. recent three questions
	3. the partners list
	4. the doctors list
	"""
	latest_posts = Post.objects.filter(status=1).order_by('-created_on')[:3]
	other_posts = Post.objects.filter(status=1).order_by('-created_on')[3:15]
	context = {
			'title': 'Home',
			'latest_posts': latest_posts,
			'other_posts': other_posts,
			'athome': True,
		}
	set_context(request, context)
	return render(
		request,
		"blog/index.html",
		context
	)	


def categories(request):
	template_name = "blog/categories.html"
	context = {
		'title': 'Categories',
		'atcategories': True,
	}
	set_context(request, context)

	return render(request, template_name, context)

# START Filter VIEW
def filter(request):
	template = "blog/filter.html"
	context = {}
	section = request.GET.get('section')
	month = request.GET.get('month')
	year = int(request.GET.get('year'))
	items = []
	if month == 'all':
		if section == 'Posts':
			context['atposts'] = True
			context['title'] = 'Filtered Posts for ' + str(year) + '/' +str(month)
			items = Post.objects.filter(
				created_on__year=year, status=1).order_by('-created_on')
		else:
			context['atquestions'] = True
			context['title'] = 'Filtered Questions for ' + str(year) + '/' +str(month)
			items = Question.objects.filter(
				created_on__year=year, status=1).order_by('-created_on')
	else:
		month = int(month)
		if section == 'Posts':
			context['atposts'] = True
			context['title'] = 'Filtered Posts for ' + str(year) + '/' +str(month)
			items = Post.objects.filter(
				created_on__year=year, 
				created_on__month=month, status=1).order_by('-created_on')
		else:
			context['atquestions'] = True
			context['title'] = 'Filtered Questions for ' + str(year) + '/' +str(month)
			items = Question.objects.filter(
				created_on__year=year,
				created_on__month=month, status=1).order_by('-created_on')
	
	context['f_year'] = year
	context['f_month'] = month
	paginator = Paginator(items, 20) # Show 20 per page.
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context['page_obj'] = page_obj
	set_context(request, context)

	return render(request, template, context)
# END Filter VIEW

# START Images VIEWS
def SaveImage(request):
	file = request.FILES['image']
	img_str = convert_image(file)
	image = Image(
		title = request.POST['title'],
		data = img_str,
		group = ImageGroup.objects.get(pk=request.POST['group']),
			description = request.POST['description'],
	)
	image.save()
	return HttpResponseRedirect(reverse("blog:image_detail", args=(image.id,)))

def images(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	if request.method == "POST":
		return SaveImage(request)
	else:
		groups = ImageGroup.objects.all()
		context = {
				"title": "Images",
				"groups": groups,
				'atimages': True,
			}
		set_context(request, context, False)
		return render(
			request,
			'images/index.html',
			context
		)

def images_group(request, pk):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	if request.method == "POST":
		return SaveImage(request)
	else:
		template_name = 'images/images_group.html'
		group = get_object_or_404(ImageGroup, pk=pk)
		images = group.images.all()
		context = {
			'title': "Images in " + group.name,
			'group': group,
			'groups': ImageGroup.objects.all(),
		}

		paginator = Paginator(images, 30) # Show 20 per page.
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		context['page_obj'] = page_obj
		set_context(request, context, False)
		return render(request, template_name, context)

def image_detail(request, image_id):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	old_image = get_object_or_404(Image, pk=image_id)
	groups = ImageGroup.objects.all()
	
	context = {
		'title': 'Image',
		'image': old_image,
		'groups': groups,
		'atimages': True,
	} 
	set_context(request, context, False)

	if request.method == "POST":
		old_image.title = request.POST['title']
		old_image.group = groups.get(pk=request.POST['group'])
		old_image.description = request.POST['description']
		if request.FILES:
			old_image.data = convert_image(request.FILES['image'])
		old_image.save()

		return HttpResponseRedirect(reverse('blog:image_detail', args=(old_image.id,)))
	else:
		return render(
			request,
			"images/image_detail.html",
			context
		)
#END Images VIEWS

# START Search VIEW
@csrf_exempt
def search(request):
	section = request.GET.get('s')
	phrase = request.GET.get('q')
	query = SearchQuery(phrase)
	items = []

	context = {
		'title': 'Search Results',
		'query': phrase,
		'section': section
	}
	set_context(request, context, True)

	if section == 'Posts':
		context['atposts'] = True
		post_vector = SearchVector('title') + SearchVector('content')
		items = Post.objects.annotate(
			search=post_vector).filter(search=query, status=1).order_by('-created_on')
	else:
		context['atquestions'] = True
		question_vector = SearchVector('content')
		items = Question.objects.annotate(
			search=question_vector).filter(search=query, status=1).order_by('-created_on')
	
	paginator = Paginator(items, 20) # Show 20 per page.
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context['page_obj'] = page_obj
	
	return render(request, 'blog/search.html', context)
	
#END Search VIEW

# START Subscribe VIEWS
def subscribe(request):
	if request.method == "POST":
		# Check for the subscriber to see if already exists
		subscribers = Subscriber.objects.filter(email=request.POST['email'])
		if subscribers: # some subscribers with the email are found
			subscribers[0].subscribed = True # subscribe the first one
			subscribers[0].save()	# save him/her then redirect
			return HttpResponseRedirect(reverse('blog:subscribed', args=(subscribers[0].id,)))
		subscriber = Subscriber(
			first_name = request.POST['first_name'],
			last_name = request.POST['last_name'],
			email = request.POST['email'],
			subscribed = True,
		)

		subscriber.save()
		return HttpResponseRedirect(reverse('blog:subscribed', args=(subscriber.id,)))
	else:
		return HttpResponseRedirect(reverse('blog:index'))

def subscribed(request, pk):
	subscriber = get_object_or_404(Subscriber, pk=pk)
	context = {
		'title': 'Successfully Subscribed',
		'subscriber': subscriber,
		'subscribed': True,
	}
	set_context(request, context, False)

	return render(request, 'blog/subscribed.html', context)

@csrf_exempt
def unsubscribe(request, pk):
	if request.method != 'POST':
		return HttpResponseRedirect(reverse('blog:index'))
	subscriber = get_object_or_404(Subscriber, pk=pk)
	c_subscriber = get_object_or_404(Subscriber, pk=int(request.POST['subscriber']))
	c_subscriber.subscribed = False
	c_subscriber.save()
	return HttpResponseRedirect(reverse('blog:unsubscribed', args=(subscriber.id,)))

def unsubscribed(request, pk):
	subscriber = get_object_or_404(Subscriber, pk=pk)
	context = {
		'title': 'Successfully Unsubscribed',
		'subscriber': subscriber,
		'subscribed': False,
	}
	set_context(request, context, False)
	return render(request, 'blog/subscribed.html', context)

def resubscribe(request, pk):
	if request.method != 'POST':
		return HttpResponseRedirect(reverse('blog:index'))
	subscriber = get_object_or_404(Subscriber, pk=pk)
	c_subscriber = get_object_or_404(Subscriber, pk=int(request.POST['subscriber']))
	c_subscriber.subscribed = True
	c_subscriber.save()
	return HttpResponseRedirect(reverse('blog:subscribed', args=(subscriber.id,)))

# END Subscribe VIEWS


def logout(request):
	return HttpResponseRedirect('/admin/logout')

blog/templates/questions/ask.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="row">
		<div class="col-md-9">
			<div class="card shadow">
				{% if new_question %}
					<div class="card-header text-success">
						<h4><i>Successfully Submitted A Question</i></h4>
					</div>
					<div class="card-body alert alert-success text-center">
						<p>Your Question is Awaiting moderation and review.</p>
						<a class="btn btn-primary" href="{% url 'blog:questions_index' %}">
							View All Questions <span class="fas fa-question"></span></a>
						<hr/>
						<a class="btn btn-success" href="{% url 'blog:questions_ask' %}">
							Ask Another Question <span class="fas fa-question"></span></a>
						
					</div>
				{% else %}
					<form action="{% url 'blog:questions_ask' %}" method="POST">
						{% csrf_token %}
						<div class="card">
							<div class="card-header">
								<h4><i><b>{{title}}</b></i></h4>
							</div>
							<div class="card-body">
								{{ form | crispy }}
							</div>
							<div class="text-right card-footer">
								<div class="row">
									<div class="col-8"></div>
									<div class="col-4">
										<button type="submit" class="btn btn-block btn-primary">
											Ask <i class="fas fa-question"></i></button>
									</div>
								</div>
							</div>
						</div>
					</form>
				{% endif %}
			</div>
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/questions/category_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	
	<div id="arrive"></div>
	<div></div>
	<div class="row">
		<div class="col-md-9">
			<h4><b>Questions in <i>{{category.name}}</i></b></h4>
			<hr/>
			{% if page_obj %}
				<ul class="list-unstyled">
					{% for question in page_obj %}
						{% include "questions/question.html" %}
					{% endfor %}
				</ul>
				{% include "pagination.html" %}
			{% else %}
				<p><i>There Are No Questions In this Category</i></p>
			{% endif %}
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/questions/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="row">
		<div class="col-md-9">
			<div class="card shadow">
				<div class="card-header">
					<h4><i><b>{{title}}</b></i></h4>
				</div>
				<div class="row card-body">
					<div class="col-md-9">
						<p class="card-text muted">
							{% if question.answer %}
								<p class="alert alert-success">Answered</p>
							{% else %}
								<p class="alert alert-danger">No Yet Answered</p>
							{% endif %}
						</p>
						<hr/>
						{{question.content|safe}}
					</div>
					<div class="col-md-3">
						<div class="card padding">
							<div class="row card-body">
								<div class="col-md-12">
									<small>Asked: <strong>{{question.created_on}}</strong></small>
									<hr/>
								</div>
								<div class="col-3 col-md-12">
									<img class="rounded-circle card-image" width="100%"
										src="{% static 'images/user.jpg' %}" />
								</div>
								<div class="col-9 col-md-12">
									<p><strong>By:</strong> <b>{{question.name}}</b></p> 
									<small><a href="mailto:{{question.email}}" target="_blank">
										{{question.email}}</a></small>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<hr/>
			{% if question.answer %}
				<div class="card shadow">
					<h5 class="card-header">{{question.answers.count}} Answer{{question.answers.count|pluralize}}</h5>
					<div class="card-body">
						{% if question.answers %}
							<div class="container">
								{% for answer in question.answers.all %}
									<div class="card shadow">
										<div class="card-body">
											{{answer.content|safe}}
										</div>
										<div class="card-header">
											<div class="row card-body">
												<div class="col-md-12">
													<small>Answered: <strong>{{answer.created_on}}</strong></small>
													<hr/>
												</div>
												<div class="col-2">
													<img class="rounded-circle card-image" width="100%"
														src="data:image/jpg;base64,{{answer.user.profile.image.data}}" />
												</div>
												<div class="col-10">
													<small><strong>By:</strong> <b>{{answer.user.profile}}</b></small><br/> 
													<small><a href="mailto:{{answer.user.email}}" target="_blank">
														{{answer.user.email}}</a></small><br/>
													<small>{{answer.user.profile.position}} @ {{answer.user.profile.employment}}</small>
												</div>
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
						{% else %}
						{% endif %}
					</div>
				</div>			
			{% endif %}
			
			<div id="arrive"></div>
			<div></div>
			<hr/>
			<div class="comment">
				{% if page_obj %}
					<h4><i>{{page_obj.object_list.count}} Comment{{page_obj.object_list.count|pluralize}}</i></h4>
					{% for comment in page_obj %}
						{% include "comments/comment.html" %}
					{% endfor %}
					
					{% include "pagination.html" %}
				{% else %}
					<p class="text-center">No Comments</p>
				{% endif %}
				<hr/>
				{% if new_comment %}
					<div class="alert alert-success text-center">
						<p><i>Your Comment is Awaiting moderation</i></p>
					</div>
				{% else %}
					{% include "comments/form.html" %}
				{% endif %}
			</div>
			<hr/>
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/questions/index.html
{% extends 'base.html' %}

{% block content %}
	
	<div id="arrive"></div>
	<div></div>
	<h4><i><b>{{title}}</b></i></h4>
	<hr/>
	<div class="row">
		<div class="col-md-9">
			{% if page_obj %}
				<ul class="list-unstyled">
					{% for question in page_obj %}
						{% include "questions/question.html" %}
					{% endfor %}
				</ul>
				{% include "pagination.html" %}
			{% else %}
				<p>There are no Questions</p>
			{% endif %}
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/questions/question.html
{% load static %}

<li class="card shadow">
	<h6 class="card-header"><b>Category: </b>{{question.category}} | 
		<small>
			{% if question.answer %}
				<b class="text-success">Answered</b>
			{% else %}
				<b class="text-danger">Not Yet Answered</b>
			{% endif %}
		</small>
	</h6>
	<div class="card-body">
		{{question.content | safe | slice:300}}
	</div>
		
	<div class="card-footer shadow">
		<div class="row card-body">
			<div class="col-md-6">
				<small>Asked: <strong>{{question.created_on}}</strong></small><br>
				<a class="btn btn-primary btn-sm btn-block" href="{% url 'blog:questions_detail' question.id %}">
					View</a>
			</div>
			<div class="col-md-6 row">
				<div class="col-2">
					<img class="rounded-circle card-image" width="100%"
						src="{% static 'images/user.jpg' %}" />
				</div>
				<div class="col-10">
					<small><strong>By:</strong> <b>{{question.name}}</b></small><br/> 
					<small><a href="mailto:{{question.email}}" target="_blank">
						{{question.email}}</a></small>
				</div>
			</div>
		</div>
	</div>
</li>
<hr/>