blog/urls.py
from . import views, views_posts, views_questions
from django.urls import path
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [

		# Feeds
    path("feed/rss", LatestPostsFeed(), name='post_feed'),
		
		# index
		path('', views.index, name="index" ),
		path('categories', views.categories, name="categories"),
		path('about', views.about, name='about'),
		path('filter', views.filter, name="filter"),
		path('search', views.search, name="search"),
		path('subscribe', views.subscribe, name="subscribe"),
		path('subscribed/<int:pk>/', views.subscribed, name="subscribed"),
		path('unsubscribe/<int:pk>/', views.unsubscribe, name="unsubscribe"),
		path('unsubscribed/<int:pk>/', views.unsubscribed, name="unsubscribed"),
		path('resubscribe/<int:pk>/', views.resubscribe, name="resubscribe"),
		
		path('admin/images/', views.images, name="images"),
		path('admin/images/group/<int:pk>/', views.images_group, name="images_group"),
		path('admin/images/<int:image_id>/', views.image_detail, name="image_detail"),

		# posts
		path("posts", views_posts.index, name="posts_index"),
		path('posts/<slug:slug>/', views_posts.detail, name='posts_detail'),
		path('posts/last/<int:days>/', views_posts.last_posts, name='posts_last'),
		path('posts/categories/<int:pk>/', views_posts.category_detail, name='posts_category'),

		# questions
		path("questions", views_questions.index, name="questions_index"),
		path("questions/ask", views_questions.ask, name='questions_ask'),
		path('questions/<int:pk>/', views_questions.detail, name='questions_detail'),
		path('questions/last/<int:days>/', views_questions.last_questions, name='questions_last'),
		path('questions/categories/<int:pk>/', views_questions.category_detail, name='questions_category'),

		path('logout', views.logout, name="logout")
]

healthtorch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_summernote.fields import SummernoteTextField

class Category(models.Model):
	"""
	The Categories of the posts under which they are made
	"""
	name = models.CharField(max_length=30)

	def __str__(self):
			return self.name

class ImageGroup(models.Model):
	"""
	Stores the image groups forexample:
		1. Users
		2. Posts
		3. Questions etc
	"""
	name = models.CharField(max_length=50)
	description = models.TextField(blank=True)

	def __str__(self):
		return self.name

class Image(models.Model):
	""" 
	Stores all the images of the System
	"""
	title = models.CharField(max_length=50)
	data = models.TextField(blank=True)
	group = models.ForeignKey(
		ImageGroup, on_delete=models.SET_NULL, null=True, blank=True,
		related_name="images")
	description = models.TextField(blank=True)
	
	def __str__(self):
		return self.title

class Profile(models.Model):
	"""
	Stores extra information about the user
	"""
	user = models.OneToOneField(
		User, on_delete=models.CASCADE)
	title = models.CharField(max_length=30, blank=True)
	phone = models.CharField(max_length=15, blank=True)
	facebook = models.CharField(verbose_name='Facebook Username',
		max_length=20, blank=True)
	bio = models.TextField(blank=True)
	address = models.CharField(max_length=100, blank=True)
	qualification = models.CharField(max_length=100, blank=True)
	profession = models.CharField(max_length=100, blank=True)
	employment = models.CharField(max_length=100, blank=True)
	position = models.CharField(max_length=100, blank=True)
	experience = models.PositiveIntegerField(default=0)
	image = models.ForeignKey(
		Image, on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		return self.title +' ' + self.user.first_name + ' ' + self.user.last_name 
	
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

class Subscriber(models.Model):
	"""
	Store all the Users Who Subscribe for timely updates
	"""
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(max_length=100)
	subscribed = models.BooleanField(default=True)

	def __str__(self):
		return self.email
	
	def name(self):
		return self.first_name + ' ' + self.last_name

class About(models.Model):
	site_title = models.CharField(max_length=200)
	info = models.TextField()
	last_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "About Us"

class Partner(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=100)
	phone = models.CharField(max_length=30)
	website = models.CharField(max_length=100)
	address = models.CharField(max_length=400)
	image = models.ForeignKey(
		Image, related_name="partners", on_delete=models.SET_NULL, 
		null=True, blank=True)
	description = SummernoteTextField()
	active = models.BooleanField(default=True)
	created_on = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		ordering = ['-created_on']

	def __str__(self):
		return self.name

blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from .models_posts import PostComment
from .models_questions import Question, QuestionComment

class PostCommentForm(forms.ModelForm):
	class Meta:
		model = PostComment
		fields = ('name', 'email', 'body')

		widgets = {
			'body': SummernoteWidget()
		}

class QuestionCommentForm(forms.ModelForm):
	class Meta:
		model = QuestionComment
		fields = ('name', 'email', 'body')

		widgets = {
			'body': SummernoteWidget()
		}

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ('name', 'email', 'category', 'content')

		widgets = {
			'content': SummernoteWidget()
		}

blog/views.py
import base64
import datetime
from django.views import generic
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import (Paginator, PageNotAnInteger, EmptyPage)
from django.contrib.auth.models import Group, User

from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.utils import timezone
from django.contrib.postgres.search import SearchQuery, SearchVector

from .models import Image, ImageGroup, Category, Subscriber, About, Partner
from .models_posts import Post
from .models_questions import Question


def set_context(request, context, search=True):
	context['c_user'] = request.user
	context['search'] = search
	context['categories'] = Category.objects.all()
	context['partners'] = Partner.objects.filter(active=True)
	
def about(request):
	author_group = Group.objects.filter(name="Authors")[0]
	authors = User.objects.filter(groups=author_group.id)
	about = About.objects.all()
	
	if about:
		about = about[0]

	context = {
			'authors': authors,
			'about': about,
			'atabout': True,
			"title": "About Us"
		}
	set_context(request, context, False)

	return render(	
		request,
		"blog/about.html",
		context
	)

def convert_image(file):
	blob = file.read()
	b64 = base64.b64encode(blob)
	img_str = b64.decode('UTF-8')
	return img_str	

def index(request):
	"""
	returns the: 
	1. recent three posts
	2. recent three questions
	3. the partners list
	4. the doctors list
	"""
	latest_posts = Post.objects.filter(status=1).order_by('-created_on')[:3]
	other_posts = Post.objects.filter(status=1).order_by('-created_on')[3:15]
	context = {
			'title': 'Home',
			'latest_posts': latest_posts,
			'other_posts': other_posts,
			'athome': True,
		}
	set_context(request, context)
	return render(
		request,
		"blog/index.html",
		context
	)	


def categories(request):
	template_name = "blog/categories.html"
	context = {
		'title': 'Categories',
		'atcategories': True,
	}
	set_context(request, context)

	return render(request, template_name, context)

# START Filter VIEW
def filter(request):
	template = "blog/filter.html"
	context = {}
	section = request.GET.get('section')
	month = request.GET.get('month')
	year = int(request.GET.get('year'))
	items = []
	if month == 'all':
		if section == 'Posts':
			context['atposts'] = True
			context['title'] = 'Filtered Posts for ' + str(year) + '/' +str(month)
			items = Post.objects.filter(
				created_on__year=year, status=1).order_by('-created_on')
		else:
			context['atquestions'] = True
			context['title'] = 'Filtered Questions for ' + str(year) + '/' +str(month)
			items = Question.objects.filter(
				created_on__year=year, status=1).order_by('-created_on')
	else:
		month = int(month)
		if section == 'Posts':
			context['atposts'] = True
			context['title'] = 'Filtered Posts for ' + str(year) + '/' +str(month)
			items = Post.objects.filter(
				created_on__year=year, 
				created_on__month=month, status=1).order_by('-created_on')
		else:
			context['atquestions'] = True
			context['title'] = 'Filtered Questions for ' + str(year) + '/' +str(month)
			items = Question.objects.filter(
				created_on__year=year,
				created_on__month=month, status=1).order_by('-created_on')
	
	context['f_year'] = year
	context['f_month'] = month
	paginator = Paginator(items, 20) # Show 20 per page.
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context['page_obj'] = page_obj
	set_context(request, context)

	return render(request, template, context)
# END Filter VIEW

# START Images VIEWS
def SaveImage(request):
	file = request.FILES['image']
	img_str = convert_image(file)
	image = Image(
		title = request.POST['title'],
		data = img_str,
		group = ImageGroup.objects.get(pk=request.POST['group']),
			description = request.POST['description'],
	)
	image.save()
	return HttpResponseRedirect(reverse("blog:image_detail", args=(image.id,)))

def images(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	if request.method == "POST":
		return SaveImage(request)
	else:
		groups = ImageGroup.objects.all()
		context = {
				"title": "Images",
				"groups": groups,
				'atimages': True,
			}
		set_context(request, context, False)
		return render(
			request,
			'images/index.html',
			context
		)

def images_group(request, pk):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	if request.method == "POST":
		return SaveImage(request)
	else:
		template_name = 'images/images_group.html'
		group = get_object_or_404(ImageGroup, pk=pk)
		images = group.images.all()
		context = {
			'title': "Images in " + group.name,
			'group': group,
			'groups': ImageGroup.objects.all(),
		}

		paginator = Paginator(images, 30) # Show 20 per page.
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		context['page_obj'] = page_obj
		set_context(request, context, False)
		return render(request, template_name, context)

def image_detail(request, image_id):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/admin')
	old_image = get_object_or_404(Image, pk=image_id)
	groups = ImageGroup.objects.all()
	
	context = {
		'title': 'Image',
		'image': old_image,
		'groups': groups,
		'atimages': True,
	} 
	set_context(request, context, False)

	if request.method == "POST":
		old_image.title = request.POST['title']
		old_image.group = groups.get(pk=request.POST['group'])
		old_image.description = request.POST['description']
		if request.FILES:
			old_image.data = convert_image(request.FILES['image'])
		old_image.save()

		return HttpResponseRedirect(reverse('blog:image_detail', args=(old_image.id,)))
	else:
		return render(
			request,
			"images/image_detail.html",
			context
		)
#END Images VIEWS

# START Search VIEW
@csrf_exempt
def search(request):
	section = request.GET.get('s')
	phrase = request.GET.get('q')
	query = SearchQuery(phrase)
	items = []

	context = {
		'title': 'Search Results',
		'query': phrase,
		'section': section
	}
	set_context(request, context, True)

	if section == 'Posts':
		context['atposts'] = True
		post_vector = SearchVector('title') + SearchVector('content')
		items = Post.objects.annotate(
			search=post_vector).filter(search=query, status=1).order_by('-created_on')
	else:
		context['atquestions'] = True
		question_vector = SearchVector('content')
		items = Question.objects.annotate(
			search=question_vector).filter(search=query, status=1).order_by('-created_on')
	
	paginator = Paginator(items, 20) # Show 20 per page.
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context['page_obj'] = page_obj
	
	return render(request, 'blog/search.html', context)
	
#END Search VIEW

# START Subscribe VIEWS
def subscribe(request):
	if request.method == "POST":
		# Check for the subscriber to see if already exists
		subscribers = Subscriber.objects.filter(email=request.POST['email'])
		if subscribers: # some subscribers with the email are found
			subscribers[0].subscribed = True # subscribe the first one
			subscribers[0].save()	# save him/her then redirect
			return HttpResponseRedirect(reverse('blog:subscribed', args=(subscribers[0].id,)))
		subscriber = Subscriber(
			first_name = request.POST['first_name'],
			last_name = request.POST['last_name'],
			email = request.POST['email'],
			subscribed = True,
		)

		subscriber.save()
		return HttpResponseRedirect(reverse('blog:subscribed', args=(subscriber.id,)))
	else:
		return HttpResponseRedirect(reverse('blog:index'))

def subscribed(request, pk):
	subscriber = get_object_or_404(Subscriber, pk=pk)
	context = {
		'title': 'Successfully Subscribed',
		'subscriber': subscriber,
		'subscribed': True,
	}
	set_context(request, context, False)

	return render(request, 'blog/subscribed.html', context)

@csrf_exempt
def unsubscribe(request, pk):
	if request.method != 'POST':
		return HttpResponseRedirect(reverse('blog:index'))
	subscriber = get_object_or_404(Subscriber, pk=pk)
	c_subscriber = get_object_or_404(Subscriber, pk=int(request.POST['subscriber']))
	c_subscriber.subscribed = False
	c_subscriber.save()
	return HttpResponseRedirect(reverse('blog:unsubscribed', args=(subscriber.id,)))

def unsubscribed(request, pk):
	subscriber = get_object_or_404(Subscriber, pk=pk)
	context = {
		'title': 'Successfully Unsubscribed',
		'subscriber': subscriber,
		'subscribed': False,
	}
	set_context(request, context, False)
	return render(request, 'blog/subscribed.html', context)

def resubscribe(request, pk):
	if request.method != 'POST':
		return HttpResponseRedirect(reverse('blog:index'))
	subscriber = get_object_or_404(Subscriber, pk=pk)
	c_subscriber = get_object_or_404(Subscriber, pk=int(request.POST['subscriber']))
	c_subscriber.subscribed = True
	c_subscriber.save()
	return HttpResponseRedirect(reverse('blog:subscribed', args=(subscriber.id,)))

# END Subscribe VIEWS


def logout(request):
	return HttpResponseRedirect('/admin/logout')

blog/templates/blog/about.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class='card shadow'>
			<div class="card-header">
				<h4><i><b>{{title}}</b></i></h4>
				<h5>{{about.site_title}}</h5>
			</div>
			<div class="card-body"
				style="padding-left:5%; padding-right:5%;">
				{{about.info|safe}}
			</div>
		</div>
		<hr/>
	</div>
	{% if authors %}
		<h5 class="text-center"><i><b>Our Authors</b></i></h5>
		<div class="card-columns">
			{% for author in authors %}
				<div class="card shadow">
					<div class="card-header">
						<h5 class="card-title">{{ author.profile }}</h5>
					</div>
					<div class="card-body">
						<div class="row">
							<div class="col-3">
								<img width="100%" class="rounded" 
									src="data:image/jpg;base64,{{ author.profile.image.data }}" alt="{{author.profile}}" />
								<h6><i><b>{{author.profile.qualifications}}</b></i></h6>
							</div>
							<div class="col-9">
								<p class="card-text">
									{{author.profile.profession}} | {{author.profile.position}} @ {{author.profile.employment}}
									with {{author.profile.experience}} year{{author.profile.experience|pluralize}} of Experience
								</p>
							</div>
						</div>
					</div>
					<div class="card-footer">
						<small>
							<a href="https://facebook.com/{{author.profile.facebook}}"
								class="btn btn-primary btn-sm" target="_blank">Facebook</a>
							<a href="tel:{{author.profile.phone}}" class="btn btn-primary btn-sm" target="_blank">Phone</a>
							<a href="mailto:{{author.email}}" class="btn btn-primary btn-sm" target="_blank">Email</a>
						</small>
					</div>
				</div>
			{% endfor %}
		</div>
	{% endif %}
{% endblock content %}

blog/templates/blog/categories.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-md-9">
			<h4><i><b>All Categories</b></i></h4>
			<hr/>
			{% if categories.count %}
				<ul class="list-group">
					{% for category in categories %}
						<li class="list-group-item dropdown-toggle"
							data-toggle="collapse" href="#disp_{{category.id}}" role="button" 
							aria-haspopup="true" aria-expanded="false">{{category.name}}</li>
						<div id="disp_{{category.id}}" class="collapse card show">
							<a class="dropdown-item" 
								href="{% url 'blog:posts_category' category.id %}">
								<p style="margin-left:10px">Posts 
									<span class="badge badge-danger">{{category.posts.count}}</span>
								</p>
							</a>
							<a class="dropdown-item" 
								href="{% url 'blog:questions_category' category.id %}">
								<p  style="margin-left:10px">Questions 
									<span class="badge badge-danger">{{category.questios.count}}</span>
								</p>
							</a>
						</div>
					{% endfor %}
				</ul>
			{% else %}
				<p><i>There are No Categories</i></p>
			{% endif %}
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/blog/filter.html
{% extends "base.html" %}
{% block content %}
	<div class="row">
		<div class="col-md-9">
			<h4><i><b>{{title}}</b></i></h4>
			<hr/>
			{% if page_obj %}
				{% if atposts %}
					{% for post in page_obj %}
						{% include "posts/post.html" %}
					{% endfor %}
				{% else %}
					{% for atquestion in page_obj %}
						{% for question in page_obj %}
							{% include "questions/question.html" %}
						{% endfor %}
					{% endfor %}
				{% endif %}
			{% else %}
				<p><i>There are No Items Found!</i></p>
			{% endif %}
			{% include "pagination.html" %}
		</div>
		{% include "sidebar.html" %}
	</div>
{% endblock content %}

blog/templates/blog/image_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
		<div class='row'>
			<div class='col-sm-10'>
				<div class="card">
					<div  class="row">
						<div class="col-sm-8 text-center">
							<h4 class="card-title">Current Image</h4>
							<hr/>
							<img src="data:image/jpg;base64,{{image.data}}" alt="{{image.title}}"
								class="rounded" width="100%"/>
						</div>
						{% include "images/image_form.html" %}
					</div>
				</div>
			</div>
			<div class='col-sm-2'>
				<a href="{% url 'blog:images' %}" class="btn btn-success btn-block">All Images</a>
			</div>
		</div>
	</div>
{% endblock content %}

blog/templates/blog/images.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-8">
				<h4><i><b>Image Groups</b></i></h4>
				<hr/>
				{% if groups.count %}
					<ul class="list-group">
						{% for group in groups %}
							<li class="list-group-item dropdown-toggle"
          			data-toggle="collapse" href="#d_{{group.id}}" role="button" 
            		aria-haspopup="true" aria-expanded="false">{{group.name}}</li>
							<div id="d_{{group.id}}" class="collapse card-columns jumbotron">
								{% if group.images.count %}
									<p>
										<i><b>{{ group.images.count }} image{{ group.images.count|pluralize }}</b> in this Group</i>
									</p>
									<p class="text-right"><small>
										<a href="{% url 'blog:images_group' group.id %}"
											class="btn btn-primary">View</a>
									</small></p>
								{% else %}
									<p><i>There are No Images in </i><b>{{ group.name }}</b></p>
								{% endif %}
							</div>
						{% endfor %}
					</ul>
				{% else %}
					<p><i>There are No Image Groups.<br/>
						Please, go to Admin Dashboard and Add Some Groups.</i></p>
				{% endif %}
			</div>
			{% include "images/image_form.html" %}
		</div>
	</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
	<div class="row">
   	<div class="col-md-9">
			<div>
				<h4><i><b>Latest Posts</b></i></h4>
				<hr/>
				{% if latest_posts %}
					<div class="row card-deck">
						{% for post in latest_posts %}
							<div class="col-md-4">
								<div class="card border-success mb-3 shadow">
									<img class="card-img-top" src="data:image/jpg;base64,{{ post.image.data}}" alt="Logo"/>
									<div class="card-body text-success">
										<p class="card-text">{{ post.title }}</p>
										<small>{{ post.content|safe|slice:'70'}}</small>
									</div>
									<div class="card-footer border-success">
										<div class="row">
											<div class="card-text col-8">
												<small class="text-muted">{{ post.created_on}}</small>
											</div>
											<div class="col-4">
												<a class="btn btn-primary" href="{% url 'blog:posts_detail' post.slug %}">More</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				{% else %}
					<p><i>There are no Latest Posts</i></p>
				{% endif %}
			</div>
			{% if other_posts %}
				<hr/>
				<h4><i><b>Other Posts</b></i></h4>
				<hr/>
			
				<ul class="list-unstyled">
					{% for post in other_posts %}
						{% include "posts/post.html" %}
					{% endfor %}
				</ul>
				<div class="text-center">
					<a href="{% url 'blog:posts_index' %}" class="btn btn-primary">
						All Posts <i class="fas fa-book-open"></i></a>
				</div>
			{% endif %}
		</div>
		{% include "sidebar.html" %}
	</div>

{% endblock content %}

blog/templates/blog/search.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-md-9">
			<div id="arrive"></div>
			<div></div>
			<h6><b>{{title}} for</b> <i>"{{query}}"</i> under {{section}}</h6>
			<hr/>

			{% if page_obj %}
				{% if atposts %}
					{% for post in page_obj %}
						{% include "posts/post.html" %}
					{% endfor %}	
				{% else %}
					{% for question in page_obj %}
						{% include "questions/question.html" %}
					{% endfor %}	
				{% endif %}
				{% include "pagination.html" %}
			{% else %}
				<p><i>There are no Results Found!</i></p>
			{% endif %}
		</div>
		{% include "sidebar.html" %}
	</div>

{% endblock content %}

blog/templates/blog/subscribed.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-3"></div>
		<div class="col-6">
			<div class="card border-success">
				<div class="card-header">{{title}}</div>
				<div class="card-body">
					{% if subscribed %}
						<div class="text-success">
							<h5><b>Name:</b> <i>{{subscriber.name}}</i></h5>
							<h5><b>Email:</b> <i>{{subscriber.email}}</i></h5>
							<p style="padding:20px;">Thank You!! <br/>
								<i>You have successfully joined our mailing list.<br/>
								You will receive timely updates about the posts on this platform.</i>
							</p>
						</div>
					</div>
					<div class="card-footer text-right">
						<form action="{% url 'index:unsubscribe' subscriber.id %}" method="POST">
							{% csrf_token %}
							<input type='hidden' name="subscriber" value="{{subscriber.id}}" />
							<button type="submit" class="btn btn-danger" >Unsubscribe</button>
						</form>
					</div>
					{% else %}
						<div class="text-danger">
							<h5><b>Name:</b> <i>{{subscriber.name}}</i></h5>
							<h5><b>Email:</b> <i>{{subscriber.email}}</i></h5>
							<p style="padding:20px;"><b clas="text-danger">Sorry To See you Go!!</b><br/>
								<i>You have successfully unscribed from our mailing list.<br/>
								You will nolonger receive timely updates about the posts on this platform.</i>
							</p>
						</div>
					</div>
					<div class="card-footer text-right">
						<form action="{% url 'index:resubscribe' subscriber.id %}" method="POST">
							{% csrf_token %}
							<input type='hidden' name="subscriber" value="{{subscriber.id}}" />
							<button type="submit" class="btn btn-success" >Resubscribe</button>
						</form>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="col-3"></div>
	</div>
{% endblock content %}