blog/urls.py
from . import views, views_posts, views_questions
from django.urls import path
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [

		# Feeds
    path("feed/rss", LatestPostsFeed(), name='post_feed'),
		
		# index
		path('', views.index, name="index" ),
		path('categories', views.categories, name="categories"),
		path('about', views.about, name='about'),
		path('filter', views.filter, name="filter"),
		path('search', views.search, name="search"),
		path('subscribe', views.subscribe, name="subscribe"),
		path('subscribed/<int:pk>/', views.subscribed, name="subscribed"),
		path('unsubscribe/<int:pk>/', views.unsubscribe, name="unsubscribe"),
		path('unsubscribed/<int:pk>/', views.unsubscribed, name="unsubscribed"),
		path('resubscribe/<int:pk>/', views.resubscribe, name="resubscribe"),
		
		path('admin/images/', views.images, name="images"),
		path('admin/images/group/<int:pk>/', views.images_group, name="images_group"),
		path('admin/images/<int:image_id>/', views.image_detail, name="image_detail"),

		# posts
		path("posts", views_posts.index, name="posts_index"),
		path('posts/<slug:slug>/', views_posts.detail, name='posts_detail'),
		path('posts/last/<int:days>/', views_posts.last_posts, name='posts_last'),
		path('posts/categories/<int:pk>/', views_posts.category_detail, name='posts_category'),

		# questions
		path("questions", views_questions.index, name="questions_index"),
		path("questions/ask", views_questions.ask, name='questions_ask'),
		path('questions/<int:pk>/', views_questions.detail, name='questions_detail'),
		path('questions/last/<int:days>/', views_questions.last_questions, name='questions_last'),
		path('questions/categories/<int:pk>/', views_questions.category_detail, name='questions_category'),

		path('logout', views.logout, name="logout")
]

healthtorch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

templates/base.html
<doctype html>
<html lang='en'>
  <head>
    {% load static %}

    <title>{{title}} | HT Ug</title>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
      crossorigin="anonymous" />
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css" />
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    
    <!-- Scrollbars-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css" />
    
    <!-- Custom CSS -->
    <link rel='stylesheet', href="{% static 'stylesheets/style.css' %}" />
    
    <!-- FontAwesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
      integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
      crossorigin="anonymous" ></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" 
      integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" 
      crossorigin="anonymous" ></script>
  </head>
  <body>
    <div class="wrapper">
      {% block navigation %}
        <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-primary shadow">
          <!-- Navbar content -->
          <div class="container">
            <a class="navbar-brand" href="{% url 'blog:index' %}">Health Torch Uganda</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" 
              data-toggle="collapse" data-target="#navbarTogglerDemo02" 
              aria-controls="navbarTogglerDemo02" aria-expanded="false" 
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if athome %}active{% endif %}">
                  <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item {% if atposts %}active{% endif %}"> 
                  <a class="nav-link" href="{% url 'blog:posts_index' %}">Posts</a>
                </li>
                <li class="nav-item {% if atquestions %}active{% endif %}">
                  <a class="nav-link" href="{% url 'blog:questions_index' %}">Questions</a>
                </li>
                <li class="nav-item {% if atabout %}active{% endif %}">
                  <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>
              </ul>
              
              <ul class="navbar-nav navbar-right">
                <li class="nav-item bg-white" style="border-radius:2rem; padding: 0px 10px">
                  <a class="nav-link text-danger" 
                    href="{% url 'blog:questions_ask' %}">Ask</a>
                </li>
                {% if c_user.is_authenticated %}
                  {% if c_user.groups %}
                    <li class="nav-item">
                      <a class="nav-link" href="/admin">Dashboard</a>
                    </li>
                    <li class="nav-item {% if atimages %}active{% endif %}">
                      <a class="nav-link" href="{% url 'blog:images' %}">Images</a>
                    </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:logout' %}">
                      <span class="fas fa-sign-out-alt"></span>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      {% endblock navigation %}
      <div id="content" style="margin-top:30px">
        <div class="container">
          {% if search %}
            <div class="row">
              <div class="col-md-6"></div>
              <div class="col-md-6">
                <form class="form-inline" action="{% url 'blog:search' %}">
                  <div class="row shadow" style="margin-left: 2%;margin-right:2%">
                    <select name="s" class="col-4 form-control">
                      <option value="Posts" {% if atposts %}selected{% endif %}>Posts</option>
                      <option value="Questions" {% if atquestions %}selected{% endif %}>Questions</option>
                    </select>
                    <input class="form-control col-6" value="{% if query %}{{query}}{% endif %}" 
                      name="q" type="search" placeholder="Search ..." min="1"
                      autofocus>
                    <button class="btn btn-success col-2" type="submit">
                      <i class="fas fa-search"></i></button>
                  </div>
                </form>
              </div>
            </div>
            <hr/>
          {% endif %}

          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
    {% block footer %}
      <hr/>
      <footer class="footer bg-success">
        <div class="container">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
              <p class="text-center"><i>Get Timely Updates</i></p>
              <form action="{% url 'blog:subscribe' %}" method="POST">
                {% csrf_token %}
                <div class="row form-group">
                  <div class="col-6">
                    <input class="form-control" name="first_name" maxlength='30' 
                      type="text" placeholder='First Name'/>
                  </div>
                  <div class="col-6">
                    <input class="form-control" name="last_name" maxlength='30' 
                      type="text" placeholder='Last Name'/>
                  </div>
                </div>
                <div class="row">
                  <div class="col-8">
                    <input class="form-control" name="email" maxlength='30' 
                      type="email" placeholder='Email Address'/>
                  </div>
                  <div class="col-4">
                    <button type="submit" class="btn btn-primary btn-block">Subscribe</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="col-md-3"></div>
          </div>
          <hr/>
          <div class="row text-white">
            <div class="col-md-9">
              <h4>Useful Internal Links</h4>
              <hr/>
              <div class="row">
                <div class="col-md-4">
                  <div class="nav flex-column nav-pills">
                    <a class="btn btn-default btn-block btn-success 
                      {% if athome %}active{% endif %}" href="/">
                      Home <span class="fas fa-home"></span></a>
                    <a class="btn btn-default btn-block btn-success 
                      {% if atposts %}active{% endif %}" href="{% url 'blog:posts_index' %}">
                        Posts <span class="fas fa-book-open"></span></a>
                    <a class="btn btn-default btn-block btn-success 
                      {% if atquestions %}active{% endif %}" href="{% url 'blog:questions_index' %}">
                      Questions <span class="fas fa-question"></span></a>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="nav flex-column nav-pills">
                    <a class="btn btn-success btn-block 
                      {% if atabout %}active{% endif %}" href="{% url 'blog:about' %}" >
                      About <span class="fas fa-info"></span></a>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="nav flex-column nav-pills">
                    {% if c_user.is_authenticated %}
                      {% if c_user.groups %}
                        <a class="btn btn-success btn-block" href="/admin">
                          Dashboard <span class="fas fa-user-cog"></span></a>
                        <a class="btn btn-success btn-block 
                          {% if atimages %}active{% endif %}" href="{% url 'blog:images' %}">
                          Images <span class="fas fa-image"></span></a>
                      {% endif %}
                      <a class="btn btn-success btn-block" href="{% url 'blog:logout' %}">
                        Logout <span class="fas fa-sign-out-alt"></span></a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3 text-right">
              <a class="btn btn-primary" href='#top'> <span class="fas fa-arrow-up"></span></a>
              <hr/>
              <p>&copy; Copyright <b id='copy_year'></b></p>
              <p>Health Toruch Uganda 1.0</p>
            </div>
          </div>
        </div>
      </footer>
    {% endblock footer %}

    <!-- Scripts -->
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
      
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
      crossorigin="anonymous"></script>
    <!-- Bootstrap Table JS -->
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF/jspdf.min.js"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/print/bootstrap-table-print.min.js"></script>

    <!-- Bootstrap Graphs JS -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
    
    <!-- Text editor 
    <script 
      type="text/javascript" 
      src="//s3-us-west-1.amazonaws.com/xinha/xinha-latest/XinhaEasy.js">
      //xinha_options = {xinha_editors:  'textarea.text'}
    </script>
    -->

    <script src="{% static 'javascripts/custom.js' %}"></script>
    <script>
      var date = new Date();
      var year = date.getFullYear();
      var c_month = date.getMonth();
      document.getElementById('copy_year').innerHTML = year;
      var year_el = document.getElementById('year');
      var f_month = document.getElementById('f_month').value;
      if(year_el.value == ''){
        year_el.value = year;
      }
      document.getElementById('year').max = year;
      document.getElementById('year_lb').innerHTML = "<small><i class='fas fa-chevron-left'></i> "+ year + "<small>";
      var months = ['January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'];
      var month_el = document.getElementById('month')
      
      getMonths();
      function getMonths(){
        var opts = "<option value='all'>All</option>";
        if(parseInt(year_el.value) != year){
          month = 11;
        }else{
          month = c_month
        }
        for(i=0; i<=month;i++){
          var sel = '';
          if (parseInt(f_month) == (i+1)){
            sel = 'selected';
          }
          opts += "<option value='"+(i+1)+"' "+sel+">" + months[i]+"</option>";
        }
        month_el.innerHTML = opts;
      }
  
    </script>
  </body>
</html>

templates/pagination.html
<hr/>
<nav aria-label="Page Navigation">
  <ul class="pagination justify-content-end">
		{% if page_obj.has_previous %}
			<li class="page-item">
      	<a class="page-link" href="?page=1#arrive" tabindex="-1">
					<i class=" fas fa-angle-double-left"></i> First</a>
    	</li>
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}#arrive">
					<i class="fas fa-chevron-left"></i>Prev</a>
			</li>
		{% endif %}
    <li class="page-item">
			<a class="page-link disabled">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
			</a>
		</li>
		{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}#arrive">
				Next <i class="fas fa-chevron-right"></i></a>
			</li>
			<li class="page-item">
      	<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}#arrive">
					Last <i class=" fas fa-angle-double-right"></i></a>
    	</li>
		{% endif %}
  </ul>
</nav>

templates/sidebar.html
<div class="col-md-3">
  <div class=" card shadow" style="padding:5px">  
    <h5 class="text-center"><i>Filter By<i></h5>
    <hr/>
    <form action="{% url 'blog:filter' %}" method="GET">
      <div class="form-group input-group">
        <label for="section" class="text-right form-control">
          <small>Section</small></label>
        <select id="section" name="section" class="form-control">
          <option value="Posts" {% if atposts %}selected{% endif %}>Posts</option>
          <option value="Questions" {% if atquestions %}selected{% endif %}>Questions</option>
        </select>
      </div>
      <div class="form-group input-group">
        <label for="month" class="text-right form-control">
          <small>Month</small></label>
        <input type="hidden" value="{% if f_month %}{{f_month}}{% endif %}" id="f_month" />
        <select name="month" id='month' class="form-control">
        </select>
      </div>
      <div class="form-group input-group">
        <label id='year_lb' for="year" class="text-right form-control"></label>
        <input name="year" class="form-control" 
          type="number" onChange="getMonths()" id="year" min='2000'
          value="{% if f_year %}{{f_year}}{% endif %}"/>
      </div>
      <button type="submit" class="btn btn-block btn-success">
        Filter</button>
    </form>
    <hr/>
    <ul class="nav flex-column">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle {% if atcategories %}active{% endif %}"
          data-toggle="collapse" href="#categories" role="button" 
          aria-haspopup="true" aria-expanded="false">Categories</a>
        <div id="categories" calss="collapse show">
          {% for category in categories %}
            <a class="dropdown-item dropdown-toggle"
              data-toggle="collapse" href="#d_{{category.id}}" role="button" 
              aria-haspopup="true" aria-expanded="false">{{category.name}}</a>
            <div id="d_{{category.id}}" class="collapse">
              <a class="dropdown-item" 
                href="{% url 'blog:posts_category' category.id %}">
                <small style="margin-left:10px">Posts 
                  <span class="badge badge-danger">{{category.posts.count}}</span>
                </small>
              </a>
              <a class="dropdown-item" 
                href="{% url 'blog:questions_category' category.id %}">
                <small  style="margin-left:10px">Questions 
                  <span class="badge badge-danger">{{category.questions.count}}</span>
                </small>
              </a>
            </div>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item {% if atcategories %}active{% endif %}"
            href="{% url 'blog:categories' %}">
            All Categories <span class="badge badge-success">{{categories.count}}<span></a>
        </div>
      </li>
      
      <hr/>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
          data-toggle="collapse" href="#time" role="button" 
          aria-haspopup="true" aria-expanded="true">Periods</a>
        <div id="time" class="collapse show">
          <a class="dropdown-item dropdown-toggle"
              data-toggle="collapse" href="#p_week" role="button" 
              aria-haspopup="true" aria-expanded="false">Last 7 Days</a>
          <div id="p_week" class="collapse">
            <a class="dropdown-item" 
              href="{% url 'blog:posts_last' 7 %}">
              <small style="margin-left:10px">Posts</span>
              </small>
            </a>
            <a class="dropdown-item" 
              href="{% url 'blog:questions_last' 7 %}">
              <small style="margin-left:10px">Questions</span>
              </small>
            </a>
          </div>
          <a class="dropdown-item dropdown-toggle"
              data-toggle="collapse" href="#p_month" role="button" 
              aria-haspopup="true" aria-expanded="false">Last 30 Days</a>
          <div id="p_month" class="collapse">
            <a class="dropdown-item" 
              href="{% url 'blog:posts_last' 30 %}">
              <small style="margin-left:10px">Posts</span>
              </small>
            </a>
            <a class="dropdown-item" 
              href="{% url 'blog:questions_last' 30 %}">
              <small style="margin-left:10px">Questions</span>
              </small>
            </a>
          </div>
        </div>
      </li>
    </ul>
    <hr/>
    {% if partners %}
      <div class="text-center">
        <h5 class='text-center'><i>Partners</i></div>
        {% for partner in partners %}
          <a href="{{partner.website}}" class="text-center">
            <div class="row">
              <div class="col-4"></div>
              <div class="col-4">
                <img width="100%" src="data:image/jpg;base64,{{partner.image.data}}"
                  class="rounded-circle" />
              </div>
              <div class="col-4"></div>
              <small class="col-12">{{partner.name}}</small>
            </div>
          </a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>